# Generated by Django 4.2.1 on 2023-05-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('extra_messages', models.IntegerField(null=True)),
                ('day_limit_of_messages', models.IntegerField(null=True)),
                ('day_limit', models.DateField(null=True)),
                ('premium_status', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
